name: Tests

on:
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2 ]
        laravel: [ 10 ]
        
    environment: testing

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Laravel environment
        run: |
          cp .env.testing.example .env.testing
          sed -i 's/PAYPAL_SANDBOX_CLIENT_ID=/PAYPAL_SANDBOX_CLIENT_ID=${{ secrets.PAYPAL_SANDBOX_CLIENT_ID }}/g' .env.testing
          sed -i 's/PAYPAL_SANDBOX_CLIENT_SECRET=/PAYPAL_SANDBOX_CLIENT_SECRET=${{ secrets.PAYPAL_SANDBOX_CLIENT_SECRET }}/g' .env.testing

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, bcmath
          tools: composer:v2
          coverage: none
          ini-values: error_reporting=E_ALL

      - name: Set Laravel Version
        run: composer require "laravel/framework:^${{ matrix.laravel }}" --no-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/pest
